### PR TITLE
feat: Publish user deletion event to Redis

### PR DESCRIPTION
**Pull request by hangy**
### What
Adds a Redis client to the Keycloak extensions

Originally: https://github.com/openfoodfacts/scrypt-password-hash-provider/pull/15

Events are pushed as maps with `xadd` and look like this (in redis-cli):
```
18) 1) "1710368647555-0"
    2) 1) "realm"
       2) "open-products-facts"
       3) "id"
       4) "c94f6f53-eb5c-433b-aaed-e4e968e806f9"
       5) "userName"
       6) "tests"
       7) "email"
       8) "bob@gmail.com"
 ```

### CODE REVIEW

**Review by john-gom — APPROVED** [review]

**Comment by john-gom** [comment]
Thanks @hangy . One of the items we discussed on the ProductOpener call was storing a list of deleted users in a table just in case there was some problem with receiving the event (and for the older applications which don't have the ability to redact user names from products yet). Did you want to look at that or should I?

**Comment by hangy** [comment]
If you already have experience in doing so with the Keycloak tables, feel free to have a look. I can also look into integrating it with this event listener.

**Comment by john-gom** [comment]
> If you already have experience in doing so with the Keycloak tables, feel free to have a look. I can also look into integrating it with this event listener.

I was thinking that we would write to the tables inside the event handler, so that the transaction is guaranteed. I was thinking the listener would be on the Product Opener side to trigger the user deletion Minion job

**Comment by hangy** [comment]
> I was thinking the listener would be on the Product Opener side to trigger the user deletion Minion job

I have a WIP for that https://github.com/hangy/openfoodfacts-server/commits/keycloak-redis/ still need to figure out the long running listener. I'm thinking of putting it into the incron script

**Pull request merged**
